[program:laravel-schedule]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/artisan schedule:work
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=root
numprocs=1
redirect_stderr=true
startretries=3
stdout_logfile=/var/www/storage/logs/schedule.log
stderr_logfile=/var/www/storage/logs/schedule-error.log
stopwaitsecs=3600
